# Generated by Django 3.1.2 on 2021-02-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='SNo',
            field=models.IntegerField(default=0),
        ),
    ]
